# Generated by Django 5.0.6 on 2024-06-12 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpageapp', '0002_scrapednewsdata_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapednewsdata',
            name='category',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
