# Generated by Django 5.0.7 on 2024-08-12 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpageapp', '0006_scrapednewsdata_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapednewsdata',
            name='summary_status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
